In [ ]:
#Importing Numpy library
import numpy as np

Let's define $Log~sigmoid$ and $Tan~sigmoid$ functions, including their derivative.


Log sigmod:

$$
\begin{aligned}
sig(x) &= \frac{1}{1+e^{-x}} \\
sig(x)' &= \frac{e^{-x}}{(1+e^{-x})^{2}}
\end{aligned}
$$

Tan sigmod:

$$
\begin{aligned}
tsig(x) &= \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}} \\
tsig'(x) &= \frac{4}{(e^{x} + e^{-x})^2}
\end{aligned}
$$

In [ ]:
#Defining sgimoid function
def sigmoid(x,d=False):
  if d:
    #if derivative is true
    return np.exp(-x)/np.square(1+np.exp(-x))

  return 1/(1+np.exp(-x))

#Defining tan sigmoid function
def tan_sig(x,d=False):
  if d:
    #if derivative is true
    return 4/np.square(np.exp(x)+np.exp(-x))
  return (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))

```mermaid
flowchart LR
    %% Input Layer
    I1((I1))
    I2((I2))

    %% Hidden Layer
    H1((1))
    H2((2))
    H3((3))

    %% Output Layer
    O1((1))

    %% Connections with straight-line syntax
    I1 --->|v11| H1
    I1 --->|v12| H2
    I1 --->|v13| H3
    I2 --->|v21| H1
    I2 --->|v22| H2
    I2 --->|v23| H3

    H1 --->|w11| O1
    H2 --->|w21| O1
    H3 --->|w31| O1

    O1 ---> O((O))

    %% Formatting to keep it clean
    classDef default fill:#fff,stroke:#333,stroke-width:1px;
```

Let input and output be

$input~,~x~=~[0.5,-0.4]$  
$output~,~y~=~[0.15]$


Let initial weights [v] and [w] be as follows.

$$
[v]~=~\begin{bmatrix}
v_{11} & v_{12} & v_{13}\\
v_{21} & v_{22} & v_{23}
\end{bmatrix}~=~
\begin{bmatrix}
0.2 & 0.4 & 0.3\\
0.1 & 0.6 & 0.5
\end{bmatrix}
$$

$$
[w]~=~\begin{bmatrix}
w_{11}\\
W_{21}\\
w_{31}
\end{bmatrix}~=~
\begin{bmatrix}
0.1\\
0.2\\
0.1
\end{bmatrix}
$$

Using backpropagation, we can update these weight [v] and [w].

In [ ]:
x = np.array([[0.5],[-0.4]]) #Input
y = np.array([[0.15]]) #Output

vi = np.array([[0.2,0.4,0.3],[0.1,0.6,0.5]]) #Initial [V]
wi = np.array([[0.1],[0.2],[0.1]]) #Initial [W]
eta = 0.2

iterations = 1 #Number of iterations
er = [] #list to store error

The flow of backpropagation alogrithm will be as follows

* Feed Forward
\begin{aligned}
h_{in} &= v^T \cdot x \\
h_{out} &= \text{sig}(h_{in}) \\
O_{in} &= w^T \cdot h_{out} \\
O_{out} &= \text{tsig}(O_{in}) \\
E &= \frac{1}{2}(y - O_{out})^2 \\
\end{aligned}

* Backpropagation
  * Updating [w]

\begin{aligned}
\frac{\partial E}{\partial O_{out}} &= -(y - O_{out}) \\
\frac{\partial O_{out}}{\partial O_{in}} &= \text{tsig}'(O_{in}) \\
\frac{\partial E}{\partial w} &= \left( \frac{\partial E}{\partial O_{out}} \cdot \frac{\partial O_{out}}{\partial O_{in}} \right) \cdot h_{out}^T \\
\Delta w &= -\eta \cdot \frac{\partial E}{\partial w} \\
w &= w+\Delta w
\end{aligned}

  * Updating [v]

\begin{aligned}
\frac{\partial h_{out}}{\partial h_{in}} &= \text{sig}'(h_{in}) \\
\delta_{hidden} &=\left( \frac{\partial E}{\partial O_{out}} \cdot \frac{\partial O_{out}}{\partial O_{in}} \right) \cdot w  \cdot \frac{\partial h_{out}}{\partial h_{in}} \\
\frac{\partial E}{\partial v} &= \delta_{hidden} \cdot x^T \\
\Delta v &= -\eta \cdot \frac{\partial E}{\partial v}\\
v &= v+\Delta v
\end{aligned}

In [ ]:
while iterations>0:
  iterations-=1
  #Feed Forward
  input_o = x
  hi = vi.T@input_o
  ho = sigmoid(hi)
  #Calculating output
  Oi = wi.T@ho
  Oo = tan_sig(Oi)
  #Calculating error
  error = 0.5*(y - Oo)**2
  er.append(error) #store error

  #<------Back Propagation--->
  #Updating [W]
  dEdOo1 = -(y-Oo)
  dOo1dOi1 = tan_sig(Oi,d=True)
  dEdw = dEdOo1*dOo1dOi1*ho
  dW = -eta*dEdw
  wi = wi + dW
  #-----------
  #Updating [V]
  dHodHi = sigmoid(hi,d=True)
  dEdv =  dEdOo1*dOo1dOi1*wi*dHodHi*input_o.T
  dV = -eta*dEdv.T
  vi = vi + dV

  vi = np.around(vi,2)
  wi = np.around(wi,2)

#Updated weights after iteration
print('Updated weights v & w are:\n')
print(f"vi=\n{vi}\n")
print(f"wi=\n{wi}")

Updated weights v & w are:

vi=
[[0.2 0.4 0.3]
 [0.1 0.6 0.5]]

wi=
[[0.1]
 [0.2]
 [0.1]]


The example problem for this implementation was adapted from book mentioned below (`Example 10.2.5`, page 197).

---

Reference

1. D. K. Pratihar, Soft Computing: Fundamentals and Applications, Narosa Publications, New Delhi, 2014